// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1qrzy5vE0ZI3b5gd_1nIgAuFjWzJ8b3s',
    appId: '1:456972413506:web:cb8f885c7eb5915d3d5bdb',
    messagingSenderId: '456972413506',
    projectId: 'memoiros-app',
    authDomain: 'memoiros-app.firebaseapp.com',
    storageBucket: 'memoiros-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0xBvC4FAkCfcPiAfPGZP_KMhjodl-BTs',
    appId: '1:456972413506:android:806085389ca4ae7e3d5bdb',
    messagingSenderId: '456972413506',
    projectId: 'memoiros-app',
    storageBucket: 'memoiros-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBie3WJwLtDyd0oD6omlXqlg-HNbi4u1IM',
    appId: '1:456972413506:ios:776414775b42c3e33d5bdb',
    messagingSenderId: '456972413506',
    projectId: 'memoiros-app',
    storageBucket: 'memoiros-app.firebasestorage.app',
    iosBundleId: 'com.example.lifeos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBie3WJwLtDyd0oD6omlXqlg-HNbi4u1IM',
    appId: '1:456972413506:ios:776414775b42c3e33d5bdb',
    messagingSenderId: '456972413506',
    projectId: 'memoiros-app',
    storageBucket: 'memoiros-app.firebasestorage.app',
    iosBundleId: 'com.example.lifeos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1qrzy5vE0ZI3b5gd_1nIgAuFjWzJ8b3s',
    appId: '1:456972413506:web:08fec160bab123893d5bdb',
    messagingSenderId: '456972413506',
    projectId: 'memoiros-app',
    authDomain: 'memoiros-app.firebaseapp.com',
    storageBucket: 'memoiros-app.firebasestorage.app',
  );
}
